spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  jpa:
    generate-ddl: false
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: "true"
  main:
    allow-bean-definition-overriding: true
server:
  port: "8081"
springdoc:
  swagger-ui:
    path: /swagger-ui.html